export const INCREMENT_COUNTER_REQUEST = 'INCREMENT_COUNTER_REQUEST';
export const INCREMENT_COUNTER_SUCCESS = 'INCREMENT_COUNTER_SUCCESS';
export const INCREMENT_COUNTER_FAILURE = 'INCREMENT_COUNTER_FAILURE';
